---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family in ['RedHat', 'Rocky']

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'

- ansible.builtin.include_tasks: setup-Suse.yml
  when: ansible_os_family == 'Suse'

- ansible.builtin.include_tasks: setup-Windows.yml
  when: ansible_os_family == 'Windows'

# Setup user accounts
- ansible.builtin.include_tasks: users.yml
  when: ansible_os_family != 'Windows'

- ansible.builtin.include_tasks: users-Windows.yml
  when: ansible_os_family == 'Windows'
