---
- hosts: hosts:!windows
  roles:
    # Setup filesystem and network configuration before other roles
    - zfs
    - netplan
- hosts: hosts
  roles:
    - common
- hosts: hosts:&lxd:!windows
  roles:
    - lxd
  tasks:
    - ansible.builtin.include_role:
        name: incus
        tasks_from: install
- hosts: hosts:&incus:!windows
  roles:
    - incus
- hosts: hosts:!windows
  roles:
    - libvirt
    - rasdaemon
