- hosts: node_standalone
  roles:
    - common
    - common-node
    - compilers
    - cross-compilers
    - babeltrace
    - librseq
    - liburcu
    - lttng-ust
    - lttng-tools
    - lttng-modules
    - libs-i386
    # Standalone (root) nodes should use fixed IP addresses
    # DHCP can be flaky during destructive tests which change
    # the date of the system.
    - netplan
