---

# The core pattern is used by the CI containers
- when: ansible_virtualization_role == "host" or (ansible_virtualization_role == "guest" and ansible_virtualization_type == "kvm")
  block:
    - name: 'Set core pattern for reboot'
      ansible.builtin.copy:
        dest: '/etc/sysctl.d/10-core_pattern.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
        content: "kernel.core_pattern /tmp/core.%p\n"
    - name: 'Check current core pattern'
      ansible.builtin.command:
        argv: ['cat', '/proc/sys/kernel/core_pattern']
      register: current_core_pattern
    - name: 'Update current core pattern'
      when: current_core_pattern.stdout|trim != lxd_core_pattern
      ansible.builtin.command:
        argv: ['sysctl', '-w', "kernel.core_pattern='{{lxd_core_pattern}}'"]


- name: Install LXD
  ansible.builtin.apt:
    name: lxd
- name: Ensure LXD service is running
  ansible.builtin.systemd:
    name: lxd
    state: started
    enabled: true
- name: LXD Init
  block:
    - ansible.builtin.file:
        path: /etc/lxd
        state: directory
        owner: root
        group: root
        mode: '0750'
    - ansible.builtin.template:
        dest: /etc/lxd/lxd_init.yml
        src: init.yaml.j2
        owner: root
        group: root
        mode: '0600'
      register: lxd_init_template
    - ansible.builtin.shell:
        cmd: 'lxd init --preseed=true < /etc/lxd/lxd_init.yml'
      when: lxd_init_template.changed
