---
- when: netplan_manage
  block:
    - name: Install netplan
      ansible.builtin.apt:
        name: netplan.io
    - name: Update netplan default.yaml
      ansible.builtin.copy:
        content: "{{netplan_content}}"
        dest: /etc/netplan/default.yaml
        owner: root
        group: root
        mode: '0600'
      register: netplan_default_yaml
    - name: Disable ifupdown on Debian
      when: ansible_distribution == "Debian"
      block:
        - name: Disable ifupdown networking
          ansible.builtin.systemd:
            name: networking.service
            masked: true
        - name: Enable systemd-networkd
          ansible.builtin.systemd:
            name: systemd-networkd
            enabled: true
            state: started
    - name: Apply netplan
      when: netplan_default_yaml.changed and netplan_apply
      ansible.builtin.command:
        argv: ['netplan', 'apply']
