---
babeltrace_packages:
  - chrpath
  - docbook5-style-xsl
  - elfutils-devel
  - glib2-devel
  - libuuid-devel
  - popt-devel
  - python36-devel
  - python3-pip
  - python3-sphinx
  - rubygem-asciidoctor
  - swig
