---
babeltrace_packages:
  - chrpath
  - elfutils-devel
  - glib2-devel
  - libuuid-devel
  - popt-devel
  - python36-devel
  - python3-pip
  - python3-sphinx
  - swig

babeltrace_packages_pip:
  - pytest-tap  # optional dependency
  - pytest  # the version shipped with EL8 is too old
  - pytest-xdist
