---
babeltrace_packages:
  - chrpath
  - docbook5-style-xsl
  - elfutils-devel
  - glib2-devel
  - libuuid-devel
  - popt-devel
  - python3-devel
  - python3-pip
  - python3-pytest
  - python3-pytest-xdist
  - python3-sphinx
  - rubygem-asciidoctor
  - swig

babeltrace_packages_pip:
  - pytest-tap  # optional dependency

# 3.4+ requires pytest with the Config object,
# which isn't in pytest 6.2.2 from the system package.
babeltrace_pytest_tap_version: '3.3'
