---
babeltrace_packages:
  - chrpath
  - elfutils-devel
  - glib2-devel
  - libuuid-devel
  - popt-devel
  - python3-devel
  - python3-pip
  - python3-pytest
  - python3-pytest-xdist
  - python3-sphinx
  - swig

babeltrace_packages_pip:
  - pytest-tap  # optional dependency
