---
babeltrace_packages:
  - chrpath
  - docbook5-xsl-stylesheets
  - glib2-devel
  - glib2-devel-static
  - libdw-devel
  - libelf-devel
  - libuuid-devel
  - popt-devel
  - python3-devel
  - python3-pip
  - python3-pytest
  - python3-pytest-xdist
  - python3-Sphinx
  - ruby3.4-rubygem-asciidoctor
  - swig
