---
babeltrace_packages:
  - chrpath
  - glib2-devel
  - glib2-devel-static
  - libdw-devel
  - libelf-devel
  - libuuid-devel
  - popt-devel
  - python3-devel
  - python3-pip
  - python3-pytest
  - python3-pytest-xdist
  - python3-Sphinx
  - swig

babeltrace_packages_pip:
  - pytest-tap
