---

- name: Activate SLES Products
  when: ansible_distribution == 'SLES'
  include_role:
    name: suse
    tasks_from: product
  loop: "{{common_node_products|default([])}}"
  loop_control:
    loop_var: 'product'

- name: Ensure common_node patterns are installed.
  zypper: "name={{ common_node_patterns }} type=pattern state=present update_cache=yes"

- name: Ensure common_node packages are installed.
  zypper: "name={{ common_node_packages }} type=package state=present update_cache=yes"

- name: Install maven from upstream binary
  when: ansible_distribution_major_version == "12"
  block:
    - name: Create directory in /opt
      ansible.builtin.file:
        path: '/opt/apache'
        state: 'directory'
    - name: Download release
      ansible.builtin.get_url:
        url: 'https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz'
        checksum: 'sha512:https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz.sha512'
        dest: '/opt/apache'
    - name: Unarchive release
      ansible.builtin.unarchive:
        dest: '/opt/apache/'
        src: '/opt/apache/apache-maven-3.9.6-bin.tar.gz'
        remote_src: true
        creates: '/opt/apache/apache-maven-3.9.6'
    - name: Link /opt/apache/maven to latest version
      ansible.builtin.file:
        dest: '/opt/apache/maven'
        state: 'link'
        src: '/opt/apache/apache-maven-3.9.6'

- name: Set default java runtime
  when: ansible_distribution_major_version == "12"
  community.general.alternatives:
    name: java
    path: "/usr/lib64/jvm/jre-11-openjdk/bin/java"

- name: Deactivate firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: false
    state: stopped
  # The package may be not installed by default on some versions,
  # or it was manually purged.
  ignore_errors: true
