---
- name: Update apk cache.
  apk: update_cache=yes

- name: Ensure cross-compilers packages are installed.
  when: cross_compilers_install|default(true)
  apk: "name={{ cross_compilers_packages }} state=present"
