---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure babeltrace build dependencies are installed.
  apt: "name={{ babeltrace_packages }} state=present"

- name: Ensure babeltrace test dependencies are installed
  ansible.builtin.pip:
    name: "{{babeltrace_packages_pip|default([])}}"
    extra_args: '--break-system-packages'
