---
compilers_packages:
  - gcc
  - gcc-9
  - gcc-10
  - g++
  - g++-9
  - g++-10
  - clang
  - clang-9
  - clang-11
  - clang-13
  - libclang-dev
  - libclang-9-dev
  - libclang-11-dev
  - libclang-13-dev
  - clang-format
  - clang-format-9
  - clang-format-11
  - clang-format-13
  - clang-tidy
  - clang-tidy-9
  - clang-tidy-11
  - clang-tidy-13
  - bear
