---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{item}}"
  with_first_found:
    - files:
        - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
        - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
        - "{{ansible_distribution}}.yml"
        - "{{ansible_os_family}}.yml"
      skip: true
- name: OS-specific setup
  ansible.builtin.include_tasks: "{{item}}"
  with_first_found:
    - files:
        - "setup-{{ansible_os_family}}.yml"
      skip: true
- name: Deploy docker network configuration
  block:
    - name: Create docker configuration directory
      ansible.builtin.file:
        path: '/etc/docker'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'
    - name: Copy docker configuration
      ansible.builtin.copy:
        src: 'daemon.json'
        dest: '/etc/docker/daemon.json'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - 'Restart docker'
- name: Install docker
  ansible.builtin.package:
    name: "{{docker_packages}}"
- name: Ensure docker is running
  ansible.builtin.service:
    name: 'docker'
    state: 'started'
