---

- name: Add SLES products
  when: ansible_distribution == 'SLES'
  include_role:
    name: suse
    tasks_from: product
  loop: "{{docker_sles_products|default([])}}"
  loop_control:
    loop_var: product

- ansible.builtin.set_fact:
    docker_packages: "{{docker_SLES_packages}}"
