---
vm_defaults:
  memory: 4194304
  vcpu: 2
  pool: default
  disk_capacity: '80G'
  net_bridge: 'br102'
  # Non-default keys
  # cdrom: /path/to/file.iso
  # uuid: xxxx-yyyy
  # name: xyz
isos:
  - url: https://releases.ubuntu.com/jammy/ubuntu-22.04.4-live-server-amd64.iso
    checksum: "sha256:45f873de9f8cb637345d6e66a583762730bbea30277ef7b32c9c3bd6700a32b2"
    dest: /var/lib/iso/ubuntu-22.04.4-live-server-amd64.iso
  - url: https://cdimage.debian.org/cdimage/archive/12.0.0/i386/iso-cd/debian-12.0.0-i386-netinst.iso
    checksum: "sha256:4f5cf17c611693d494c0a6a591b2d1e5fcd222d95e81bc555b581b2b01488f14"
    dest: /var/lib/iso/debian-12.0.0-i386-netinst.iso
  - url: https://cdimage.debian.org/cdimage/archive/12.0.0/amd64/iso-cd/debian-12.0.0-amd64-netinst.iso
    checksum: "sha256:3b0e9718e3653435f20d8c2124de6d363a51a1fd7f911b9ca0c6db6b3d30d53e"
    dest: /var/lib/iso/debian-12.0.0-amd64-netinst.iso
  # Patched iPXE.iso with serial console + reboot + infinite timeout for LAVA
  # @see https://wiki.internal.efficios.com/lava#special_ipxe_boot_image_for_vms
  - url: http://obj.internal.efficios.com/lava/ipxe.iso
    checksum: "sha256:063bcfc9f9797636a97ccbf9dc5f52f54a85b87b0d143150102f80b8533b2f20"
    dest: /var/lib/iso/ipxe.iso
