---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define libs_i386_packages.
  set_fact:
    libs_i386_packages: "{{ __libs_i386_packages | list }}"
  when: libs_i386_packages is not defined

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Install libs from the default package manager
- ansible.builtin.package:
    name: "{{libs_i386_packages}}"
