---
# @TODO: Remove pins
# @TODO: Should 3rd party sources be removed?
# @TODO: Ensure kernel package is installed
# @TODO: Should a 2nd sshd be started on a non-standard port in case of failure?
- name: dpkg audit
  ansible.builtin.command:
    cmd: 'dpkg --audit'

- name: show holds
  ansible.builtin.command:
    cmd: 'apt-mark showhold'

- name: remove all holds
  ansible.builtin.command:
    cmd: "apt-mark unhold '*'"

- name: Replace release in apt sources.list
  ansible.builtin.replace:
    regexp: "{{ansible_distribution_release}}"
    replace: "{{next_release}}"
    path: /etc/apt/sources.list

- name: Replace release in apt sources.list.d
  ansible.builtin.shell:
    cmd: "sed -i 's/{{ansible_distribution_release}}/{{next_release}}/' /etc/apt/sources.list.d/*"
  ignore_errors: true

- ansible.builtin.apt:
    update_cache: true

- name: Check space required during upgrades
  ansible.builtin.shell:
    cmd: "apt-get --assume-no full-upgrade | grep -E '^After this operation' | cut -d ',' -f 2 | cut -d ' ' -f 2,3"
  environment:
    LANG: 'C'
  register: apt_get_full_upgrade_no_action
  ignore_errors: true

- name: Check available disk space
  ansible.builtin.command:
    cmd: 'df -k --output=avail /'
  register: diskfree_output

- ansible.builtin.set_fact:
    disk_space_available: "{{diskfree_output.stdout_lines[1] | ansible.builtin.human_to_bytes(default_unit='K')}}"
    disk_space_required: "{{apt_get_full_upgrade_no_action.stdout_lines[0] | ansible.builtin.human_to_bytes}}"

- ansible.builtin.debug:
    msg:
      - "Space required: {{disk_space_required}} bytes"
      - "Space required with margin: {{disk_space_required|int * 2}}"
      - "Space available: {{disk_space_available}} bytes"

- name: Abort if insufficient space
  when: (disk_space_required|int * 2) > disk_space_available|int
  block:
    - ansible.builtin.replace:
        replace: "{{ansible_distribution_release}}"
        regexp: "{{next_release}}"
        path: /etc/apt/sources.list
    - name: Replace release in apt sources.list.d
      ansible.builtin.shell:
        cmd: "sed -i 's/{{next_release}}/{{ansible_distribution_release}}/' /etc/apt/sources.list.d/*"
      ignore_errors: true
    - ansible.builtin.meta: end_host

- name: Download packages
  ansible.builtin.command:
    cmd: 'apt-get -y -d upgrade {{apt_common_options}}'
  environment: "{{apt_noninteractive_environment}}"

- name: Minimal upgrade run
  ansible.builtin.command:
    cmd: 'apt-get upgrade -y --without-new-pkgs {{apt_common_options}}'
  environment: "{{apt_noninteractive_environment}}"

- name: Full upgrade run
  ansible.builtin.command:
    cmd: 'apt-get full-upgrade -y {{apt_common_options}}'
  environment: "{{apt_noninteractive_environment}}"

- name: Offline jenkins nodes
  when: jenkins_node_regex|default(false)
  delegate_to: localhost
  ansible.builtin.command:
    argv: [
    '../scripts/manage_jenkins_node.py', 'disable', '--wait', '-1',
    '--reason', 'Ansible: debian_release_upgrade', '--force-abort',
    "{{jenkins_node_regex}}"]
  retries: 3

- name: Evacuate incus node
  when: incus_evacuate_node|default(false)
  ansible.builtin.command:
    argv: ['incus', 'cluster', 'evacuate', '--force', '--action', 'stop', "{{incus_evacuate_node}}"]

- name: Stop libvirt guests
  ansible.builtin.service:
    name: libvirt-guests.service
    state: stopped
  ignore_errors: true

# @TODO: reconfigure grub if installed
# `dpkg-reconfigure grub-pc` on many systems, but not all
# @TODO: Our instances often have an OS version identifier,
# it would be handy to do a replace in /etc/hostname
# before rebooting
- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Restore incus node
  when: incus_evacuate_node|default(false)
  ansible.builtin.command:
    argv: ['incus', 'cluster', 'restore', '--force', "{{incus_evacuate_node}}"]

- name: Online jenkins nodes
  when: jenkins_node_regex|default(false)
  delegate_to: localhost
  ansible.builtin.command:
    argv: ['../scripts/manage_jenkins_node.py', 'enable', "{{jenkins_node_regex}}"]

- name: Purge configuration of removed packages
  ansible.builtin.command:
    cmd: "apt-get -y purge '~c'"
  environment: "{{apt_noninteractive_environment}}"

- name: Purge obsolete packages
  ansible.builtin.command:
    cmd: "apt-get -y purge '~o'"
  environment: "{{apt_noninteractive_environment}}"
