---
# @TODO: Remove pins
# @TODO: Should 3rd party sources be removed?
# @TODO: Ensure kernel package is installed
# @TODO: Should a 2nd sshd be started on a non-standard port in case of failure?
- name: dpkg audit
  ansible.builtin.command:
    cmd: 'dpkg --audit'

- name: show holds
  ansible.builtin.command:
    cmd: 'apt-mark showhold'

- name: remove all holds
  ansible.builtin.command:
    cmd: "apt-mark unhold '*'"

- name: Replace release in apt sources.list
  ansible.builtin.replace:
    regexp: "{{ansible_distribution_release}}"
    replace: "{{next_release}}"
    path: /etc/apt/sources.list

- name: Replace release in apt sources.list.d
  ansible.builtin.shell:
    cmd: "sed -i 's/{{ansible_distribution_release}}/{{next_release}}/' /etc/apt/sources.list.d/*"
    warn: false
  ignore_errors: true

- ansible.builtin.apt:
    update_cache: true

# @TODO: Check required disk space and available disk space
- name: Download packages
  ansible.builtin.command:
    cmd: 'apt-get -y -d upgrade {{apt_common_options}}'
    warn: false
  environment: "{{apt_noninteractive_environment}}"

- name: Minimal upgrade run
  ansible.builtin.command:
    cmd: 'apt-get upgrade -y --without-new-pkgs {{apt_common_options}}'
    warn: false
  environment: "{{apt_noninteractive_environment}}"

- name: Full upgrade run
  ansible.builtin.command:
    cmd: 'apt-get full-upgrade -y {{apt_common_options}}'
    warn: false
  environment: "{{apt_noninteractive_environment}}"

- name: Offline jenkins nodes
  when: jenkins_node_regex|default(false)
  delegate_to: localhost
  ansible.builtin.command:
    argv: [
    '../scripts/manage_jenkins_node.py', 'disable', '--wait', '-1',
    '--reason', 'Ansible: debian_release_upgrade', '--force-abort',
    jenkins_node_regex]
  retries: 3

- name: Evacuate incus node
  when: incus_evacuate_node|default(false)
  ansible.builtin.command:
    argv: ['incus', 'cluster', 'evacuate', '--action', 'stop', incus_evacuate_node]

# @TODO: reconfigure grub if installed
# `dpkg-reconfigure grub-pc` on many systems, but not all
# @TODO: Our instances often have an OS version identifier,
# it would be handy to do a replace in /etc/hostname
# before rebooting
- name: Reboot
  ansible.builtin.command: /usr/sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true
  register: last_result

- name: wait for the server to reboot
  local_action: wait_for host={{ inventory_hostname }}
               port=22
               delay=1
               timeout=300
               state=started
  when: last_result.changed
  become: false

- name: Restore incus node
  when: incus_evacuate_node|default(false)
  ansible.builtin.command:
    argv: ['incus', 'cluster', 'restore', incus_evacuate_node]

- name: Online jenkins nodes
  when: jenkins_node_regex|default(false)
  delegate_to: localhost
  ansible.builtin.command:
    argv: ['../scripts/manage_jenkins_node.py', 'enable', jenkins_node_regex]

- name: Purge configuration of removed packages
  ansible.builtin.command:
    cmd: "apt-get -y purge '~c'"
    warn: false
  environment: "{{apt_noninteractive_environment}}"

- name: Purge obsolete packages
  ansible.builtin.command:
    cmd: "apt-get -y purge '~o'"
    warn: false
  environment: "{{apt_noninteractive_environment}}"
