---
extra_root_ssh_authorized_keys:
  # yamllint disable-line rule:line-length
  - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILmmI2pn+ncFKm/fOS5+RskBGnhbMd0p399ZWEKLUQ+Q lava-master-03'
lxd_cluster_ip: 172.18.0.197
lxd_cluster:
  enabled: true
  server_address: 172.18.0.197
  member_config:
    - entity: storage-pool
      name: default
      key: source
      value: tank/lxd

netplan_manage: true
netplan_content: |
  network:
    version: 2
    renderer: networkd
    ethernets:
      enp5s0f0np0:
        dhcp4: no
    bridges:
      br102:
        interfaces:
          - enp5s0f0np0
        accept-ra: false
        addresses:
          - 172.18.0.197/16
        routes:
          - to: default
            via: 172.18.0.1
        nameservers:
          search:
            - internal.efficios.com
          addresses:
            - 172.18.0.13
