---
lxd_cluster_ip: 172.18.0.190
lxd_cluster:
  server_name: ci-host-amd64-1a
  enabled: true
  member_config:
    - entity: storage-pool
      name: default
      key: source
      value: tank/lxd
netplan_manage: true
netplan_content: |
  network:
    version: 2
    renderer: networkd
    ethernets:
      enp5s0f0np0:
        dhcp4: no
    bridges:
      br102:
        interfaces:
          - enp5s0f0np0
        accept-ra: false
        addresses:
          - 172.18.0.190/16
        routes:
          - to: default
            via: 172.18.0.1
        nameservers:
          search:
            - internal.efficios.com
          addresses:
            - 172.18.0.13
