---
lxd_cluster_ip: 172.18.0.195
lxd_cluster:
  enabled: true
  server_address: 172.18.0.195
  member_config:
    - entity: storage-pool
      name: default
      key: source
      value: tank/lxd

netplan_manage: true
netplan_content: |
  network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        match:
          macaddress: 7c:c2:55:9f:17:e0
        set-name: eth0
        dhcp4: no
    bridges:
      br102:
        interfaces:
          - eth0
        accept-ra: false
        addresses:
          - 172.18.0.195/16
        routes:
          - to: default
            via: 172.18.0.1
        nameservers:
          search:
            - internal.efficios.com
          addresses:
            - 172.18.0.13
