---
lxd_cluster_ip: 172.18.0.33
lxd_cluster:
  server_name: cloud03
  server_address: 172.18.0.33
  cluster_token: 'eyJzZXJ2ZXJfbmFtZSI6ImNsb3VkMDMiLCJmaW5nZXJwcmludCI6IjdlZTc4NmU1YTk5YjAyOGNhZWM2M2ZmMWM3ZDExNzBjMjFkYTk2NGM2ODZjNjJkNTI4NGMzYTZkYjFkMDFjYjgiLCJhZGRyZXNzZXMiOlsiMTcyLjE4LjAuMzE6ODQ0MyJdLCJzZWNyZXQiOiI3NDI5NWE0OTc4NmIyNjZlYjczMmU4OTg5ODIyYzZiY2EyODFjMmY2YWVhOWEzZGM5OTA4ODc4MGMzZDU5MGEzIiwiZXhwaXJlc19hdCI6IjIwMjQtMDgtMDhUMTE6NDE6MDIuMjI2NTM2MTgtMDQ6MDAifQ=='
  enabled: true
  member_config:
    - entity: storage-pool
      name: default
      key: source
      value: tank/lxd
netplan_manage: true
netplan_content: |
  network:
    version: 2
    renderer: networkd
    ethernets:
      enp8s0f0:
        dhcp4: no
    bridges:
      br102:
        interfaces:
          - enp8s0f0
        accept-ra: false
        addresses:
          - 172.18.0.33/16
        routes:
          - to: default
            via: 172.18.0.1
        nameservers:
          search:
            - internal.efficios.com
          addresses:
            - 172.18.0.13
