---

- name: Configure bookworm-backports
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '12'
  ansible.builtin.apt_repository:
    repo: 'deb https://deb.debian.org/debian bookworm-backports main contrib non-free-firmware'

- name: Install packages
  ansible.builtin.package:
    name:
      - incus
      - incus-tools
