---

- name: Activate required products
  when: ansible_distribution == 'SLES'
  include_role:
    name: suse
    tasks_from: product
  loop: "{{developer_sles_products|default([])}}"
  loop_control:
    loop_var: 'product'
